apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: {{ .Values.mysql.host }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_DB: {{ .Values.mysql.db }}
  MYSQL_PORT: "{{ .Values.mysql.port }}"