apiVersion: v1
kind: ConfigMap
metadata:
  name: processing-configmap
data:
    MONGO_HOST: {{ .Values.mongo.uri }}
    RABBITMQ_HOST: {{ .Values.rabbitmq.host }}
    SVC_QUEUE: {{ .Values.rabbitmq.queue }}