apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: {{ .Values.auth.svc_address }}
  MONGO_URI: {{.Values.mongo.uri }}
  RABBITMQ_HOST: {{ .Values.rabbitmq.host }}